** Add Items to an Array with push() and unshift().
- Both methods take one or more elements as parameters and add those elements to the array the method is being called on; the *push()* method adds elements to the end of an array, and *unshift()* adds elements to the beginning. Consider the following:

#+BEGIN_SRC js
let twentyThree = 'XXIII';
let romanNumerals = ['XXI', 'XXII'];

romanNumerals.unshift('XIX', 'XX');
// *romanNumerals* would have the value *['XIX', 'XX', 'XXI', 'XXII']*.

romanNumerals.push(twentyThree);
// *romanNumerals* would have the value *['XIX', 'XX', 'XXI', 'XXII', 'XXIII']*. 
//Notice that we can also pass variables, which allows us even greater flexibility in dynamically modifying our array's data.
#+END_SRC

** Remove Items from an Array with pop() and shift()
- *pop()* removes an element from the end of an array, while *shift()* removes an element from the beginning. 
#+BEGIN_SRC js

let greetings = ['whats up?', 'hello', 'see ya!'];

greetings.pop();
#+END_SRC

- greetings would have the value ['whats up?', 'hello'].
#+BEGIN_SRC js

greetings.shift();

- greetings would have the value ['hello'].
#+END_SRC

- We can also return the value of the removed element with either method like this:
#+BEGIN_SRC js

let popped = greetings.pop();
#+END_SRC

- greetings would have the value [], and popped would have the value hello.

** Could be a example this code: 
#+BEGIN_SRC js
function popShift(arr) {
  let popped = arr.pop();
  let shifted = arr.shift() ; 
  let answer = popped +' '+ shifted; //I'm not sure if this declariton it's correct 
  return [answer];
}

console.log(popShift(['challenge', 'is', 'not', 'complete']));
#+END_SRC
**** Please leave a comment or open a issue with a refactor of the above code 

*** we can use this code as well (It’s as above code, but this code was tested & already worked properly): 

#+BEGIN_SRC js
function popShift(arr) {
  let popped = arr.pop(); 
  let shifted = arr.shift() ; 
  return [shifted, popped];
}

console.log(popShift(['challenge', 'is', 'not', 'complete']));
#+END_SRC
** Add Items Using splice()
- The second occurrence of 12 is removed, and we add 13 and 14 at the same index. The numbers array would now be [ 10, 11, 12, 13, 14, 15 ].
- Here, we begin with an array of numbers. Then, we pass the following to splice(): The index at which to begin deleting elements (3), the number of elements to be deleted (1), and the remaining arguments (13, 14) will be inserted starting at that same index. Note that there can be any number of elements (separated by commas) following amountToDelete, each of which gets inserted.
#+BEGIN_SRC js

const numbers = [10, 11, 12, 12, 15];
const startIndex = 3;
const amountToDelete = 1;

numbers.splice(startIndex, amountToDelete, 13, 14);
console.log(numbers);
#+END_SRC
** Copy Array Items Using slice()
- The next method we will cover is slice(). Rather than modifying an array, slice() copies or extracts a given number of elements to a new array, leaving the array it is called upon untouched. slice() takes only 2 parameters — the first is the index at which to begin extraction, and the second is the index at which to stop extraction (extraction will occur up to, but not including the element at this index). Consider this:
#+BEGIN_SRC js
let weatherConditions = ['rain', 'snow', 'sleet', 'hail', 'clear'];

let todaysWeather = weatherConditions.slice(1, 3);
#+END_SRC

- todaysWeather would have the value ['snow', 'sleet'], while weatherConditions would still have ['rain', 'snow', 'sleet', 'hail', 'clear'].

*** Another example: 

#+BEGIN_SRC js
function forecast(arr) {
  // Only change code below this line

  return arr.slice(2,4);
}

// Only change code above this line
console.log(forecast(['cold', 'rainy', 'warm', 'sunny', 'cool', 'thunderstorms']));
#+END_SRC

** Copy an Array with the Spread Operator

- While slice() allows us to be selective about what elements of an array to copy, among several other useful tasks, ES6's new spread operator allows us to easily copy all of an array's elements, in order, with a simple and highly readable syntax. The spread syntax simply looks like this: *...*

In practice, we can use the spread operator to copy an array like so:

#+BEGIN_SRC js
let thisArray = [true, true, undefined, false, null];
let thatArray = [...thisArray]; //Output: [true, true, undefined, false, null]
#+END_SRC

** Exercise

*** We have defined a function, copyMachine which takes arr (an array) and num (a number) as arguments. The function is supposed to return a new array made up of num copies of arr. We have done most of the work for you, but it doesn't work quite right yet. Modify the function using spread syntax so that it works correctly (hint: another method we have already covered might come in handy here!).

#+BEGIN_SRC js
function copyMachine(arr, num) {
  let newArr = [];
  while (num >= 1) {
    // Only change code below this line

    // Only change code above this line
    num--;
  }
  return newArr;
}

// copyMachine([true, false, true], 2) should return [[true, false, true], [true, false, true]]

console.log(copyMachine([true, false, true], 2));
#+END_SRC

**** Solution
#+BEGIN_SRC js
newArr.push([...arr]);
#+END_SRC

** Combine Arrays with the Spread Operator

#+BEGIN_SRC
function spreadOut() {
  let fragment = ['to', 'code'];
  let sentence = ['learning', ...fragment, 'is', 'fun']
  return sentence;
}

console.log(spreadOut());
#+END_SRC

** Check For The Presence of an Element With indexOf()
*** Example 
- JavaScript provides us with another built-in method, indexOf(), that allows us to quickly and easily check for the presence of an element on an array. indexOf() takes an element as a parameter, and when called, it returns the position, or index, of that element, or -1 if the element does not exist on the array.
#+BEGIN_SRC js
let fruits = ['apples', 'pears', 'oranges', 'peaches', 'pears'];

fruits.indexOf('dates');
fruits.indexOf('oranges');
fruits.indexOf('pears');
// Output: indexOf('dates') returns -1, indexOf('oranges') returns 2, and indexOf('pears') returns 1 (the first index at which each element exists).
#+END_SRC
*** Exercise
**** We have defined a function, quickCheck, that takes an array and an element as arguments. Modify the function using indexOf() so that it returns true if the passed element exists on the array, and false if it does not.

- The quickCheck function should return a boolean (true or false), not a string ("true" or "false")

#+BEGIN_SRC js 
function quickCheck(arr, elem) {
  // Only change code below this line

  // Only change code above this line
}

console.log(quickCheck(['squash', 'onions', 'shallots'], 'mushrooms'));
#+END_SRC
**** Solution 
#+BEGIN_SRC js
  if (arr.indexOf(elem) >= 0){
    return true;
  } else {
   return false;
  }
#+END_SRC
**** Refactoring 
#+BEGIN_SRC js
    return arr.indexOf(elem) >= 0 ? true : false;
#+END_SRC